version: '3.8'

services:

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"

  spark:
    image: bitnami/spark:3.3.2-debian-11-r0
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8081:8080"
    volumes:
      - ./spark/jobs:/opt/spark/jobs
      - ./spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    depends_on:
      - minio

  airflow:
    image: apache/airflow:2.9.1
    container_name: airflow
    depends_on:
      - minio
      - spark
    ports:
      - "8088:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////root/airflow/airflow.db
      - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
      - PIP_INSTALL_REQUIREMENTS=true
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/requirements.txt:/requirements.txt
    command: >
      bash -c "pip install apache-airflow-providers-amazon && 
               airflow db init &&
               airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin &&
               airflow webserver & airflow scheduler"
